name: Refresh projects analytics every 4 hours
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  refresh-analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn generate-analytics
        env:
          FATHOM_EMAIL: ${{ secrets.FATHOM_EMAIL }}
          FATHOM_PASSWORD: ${{ secrets.FATHOM_PASSWORD }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      - name: Commit analytics changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Matthew Elphick
          author_email: matt.a.elphy@gmail.com
          message: "chore: 🤖 Update analytics data"
          add: "data/analytics.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
